### PR TITLE
Fixed Typo

### LINKED ISSUE #1: speedup-button title: The first letter should be capitalized
grafik

For tooltips the first letter should be capitalized.
Please change the tooltip according to the standard.

### PR DESCRIPTION
**Pull request by liegsalz**
A confusing capitalization of the title of an element worsened the user experience.

### CODE REVIEW

**Review by jwalteri — APPROVED** [review]
It's a beautiful fix. I could not have done it that way!

**Comment by haerrel** [comment]
Unsatisfying... will merge tho

**Comment by liegsalz** [comment]
> Unsatisfying... will merge tho

Please elaborate on your feedback

**Comment by jwalteri** [comment]
@haerrel Please publish a new version including the bug fix. Thx!

**Comment by haerrel** [comment]
@liegsalz please tag the commit as described in this github action file to release a new version

https://github.com/haerrel/bbb-playbackspeed-chrome-extension/blob/master/.github/workflows/main.yml

**Comment by liegsalz** [comment]
> @liegsalz please tag the commit as described in this github action file to release a new version
> 
> https://github.com/haerrel/bbb-playbackspeed-chrome-extension/blob/master/.github/workflows/main.yml

Thank you for your fast response. As you accepted it, the commit is under your name and your project, therefore you must tag the commit. I have no perms in your repo.

**Pull request merged**
